### ISSUE TITLE
App Crashes with WAN Adddress

### ISSUE THREAD

**Issue by weswitt** [home-assistant/home-assistant-android#121]
The app crashes 100% of the time when trying to connect to my server outside of my LAN network. It tries to scan and of course finds nothing so I type in a URL to my server and the app crashes.

**Comment by balloob** [comment]
This needs more information. Are you typing in the url with protocol? Did you try it with the 1.1.2 version released today?

**Comment by erlanger** [comment]
I get a crasth too. After the scan fails I can't even enter the URL. This is with version 1.2. I was able to obtain the logcat, it iseems it is crashing because of missing an icon resource (drawable/design_password_eye):

```
12-15 02:14:39.637 I/ActivityManager(1314): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.homeassistant.companion.android/.launch.LaunchActivity bnds=[234,800][438,1107]} from uid 10031
12-15 02:14:39.695 I/ActivityManager(1314): Start proc 12480:io.homeassistant.companion.android/u0a141 for activity io.homeassistant.companion.android/.launch.LaunchActivity
12-15 02:14:39.979 I/ActivityManager(1314): START u0 {cmp=io.homeassistant.companion.android/.onboarding.OnboardingActivity} from uid 10141
12-15 02:14:40.062 I/ActivityManager(1314): Displayed io.homeassistant.companion.android/.onboarding.OnboardingActivity: +420ms
12-15 02:14:40.342 W/SurfaceFlinger(625): Attempting to set client state on removed layer: Splash Screen io.homeassistant.companion.android#0
12-15 02:14:40.342 W/SurfaceFlinger(625): Attempting to destroy on removed layer: Splash Screen io.homeassistant.companion.android#0
12-15 02:14:46.554 E/AndroidRuntime(12480): Process: io.homeassistant.companion.android, PID: 12480
12-15 02:14:46.554 E/AndroidRuntime(12480): 	at io.homeassistant.companion.android.onboarding.manual.ManualSetupFragment.onCreateView(ManualSetupFragment.kt:46)
12-15 02:14:46.554 E/AndroidRuntime(12480): Caused by: android.content.res.Resources$NotFoundException: Drawable io.homeassistant.companion.android:drawable/design_password_eye with resource ID #0x7f07007e
12-15 02:14:46.555 E/AndroidRuntime(12480): 	at io.homeassistant.companion.android.onboarding.manual.ManualSetupFragment.onCreateView(ManualSetupFragment.kt:46)
12-15 02:14:46.556 E/AndroidRuntime(12480): 	at io.homeassistant.companion.android.onboarding.manual.ManualSetupFragment.onCreateView(ManualSetupFragment.kt:46)
12-15 02:14:46.666 W/ActivityManager(1314):   Force finishing activity io.homeassistant.companion.android/.onboarding.OnboardingActivity
12-15 02:14:46.696 W/InputDispatcher(1314): channel 'c70c26e io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-15 02:14:46.696 E/InputDispatcher(1314): channel 'c70c26e io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-15 02:14:46.702 I/WindowManager(1314): WIN DEATH: Window{c70c26e u0 io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity}
12-15 02:14:46.703 W/InputDispatcher(1314): Attempted to unregister already unregistered input channel 'c70c26e io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity (server)'
12-15 02:14:46.704 I/ActivityManager(1314): Process io.homeassistant.companion.android (pid 12480) has died: fore TOP 
12-15 02:14:46.712 W/SurfaceFlinger(625): Attempting to set client state on removed layer: io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity#0
12-15 02:14:46.712 W/SurfaceFlinger(625): Attempting to destroy on removed layer: io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity#0
12-15 02:14:46.715 W/SurfaceFlinger(625): Attempting to destroy on removed layer: AppWindowToken{ccff604 token=Token{23d6217 ActivityRecord{c597696 u0 io.homeassistant.companion.android/.onboarding.OnboardingActivity t333}}}#0
```

**Comment by balloob** [comment]
@erlanger that's another issue. 

Going to close this issue as no response from reporter.
