### ISSUE TITLE
Crash on build 37 and later

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/home-assistant-android#141]
```
Fatal Exception: io.homeassistant.companion.android.data.integration.IntegrationException
       at io.homeassistant.companion.android.data.integration.IntegrationRepositoryImpl.getZones(IntegrationRepositoryImpl.kt:81)
       at io.homeassistant.companion.android.data.integration.IntegrationRepositoryImpl$getZones$1.invokeSuspend(:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:334)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by robbiet480** [comment]
@JBassett This appears related to #129. Can you take a look?

**Comment by balloob** [comment]
Happened to me. I have one passive and the home zone defined

**Comment by JBassett** [comment]
If we don't successfully get zones from your HA instance we were crashing.  Added some error handling to gracefully fail.
