### ISSUE TITLE
App crashes on login field long press

### ISSUE THREAD

**Issue by gotson** [home-assistant/home-assistant-android#196]
**Home Assistant Android version:** 1.3.1

**Android version:** 9

**Phone model:** one plus 6t, Samsung galaxy tab s5e

**Home Assistant version:** 0.103.3

**Last working Home Assistant release (if known):** 

**Description of problem:** when long pressing the password field at login (to paste), the app crashes

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by JBassett** [comment]
Here is the exception I got when reproducing:
```
W/System.err: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x20d0032
W/System.err:     at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:279)
        at android.content.res.Resources.getResourceEntryName(Resources.java:2030)
        at com.lokalise.sdk.LokaliseResources.getText(LokaliseResources.kt:38)
W/System.err:     at com.lokalise.sdk.LokaliseResources.getString(LokaliseResources.kt:20)
        at android.content.Context.getString(Context.java:578)
        at cB.onCreateActionMode(PG:6)
        at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(DecorView.java:2637)
        at com.android.internal.policy.DecorView.startActionMode(DecorView.java:939)
W/System.err:     at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:895)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
I/chatty: uid=10082(io.homeassistant.companion.android) identical 3 lines
W/System.err:     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.View.startActionMode(View.java:6817)
W/System.err:     at dB.a(PG:4)
        at org.chromium.content.browser.selection.SelectionPopupControllerImpl.showSelectionMenu(PG:40)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6971)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
```

Looks like a Lokalise issue

**Comment by balloob** [comment]
@bramkragten where did we report the bug last time?

**Comment by bramkragten** [comment]
WIth the support team of Lokalise, I'm in contact with their Android developer, I'll send him the exception.

**Comment by bramkragten** [comment]
Do you have any more info how to reproduce this? I'm not getting any errors on the latest build.

**Comment by dshokouhi** [comment]
Is this still an issue?  Lokalize was recently updated.

**Comment by bramkragten** [comment]
https://github.com/home-assistant/home-assistant-android/pull/318
