### ISSUE TITLE
App crashes on html time input open

### ISSUE THREAD

**Issue by vilppuvuorinen** [home-assistant/home-assistant-android#221]
**Home Assistant Android version:**

1.3.1

**Android version:**

9

**Phone model:**

TA-1004

**Home Assistant version:**

0.103.0

**Last working Home Assistant release (if known):**

**Description of problem:**

I have a custom card with an `<input type="time" />`. The web app has no issues with this and cheerfully servers me the crisp and clean OS time picker and 5 start time picking experience. However, the companion app instantly crashes if I tap on the time picker.

I think I've narrowed the issue down to `LokaliseResource.getText` call as evident from the below logcat output. It seems to be a clear duplicate of #196. I have no doubts that `datetime-local` and `date` inputs suffer from the same issues. 

**Traceback (if applicable):**

```
01-03 20:48:46.990 24784 24784 W System.err: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x21302a5
01-03 20:48:46.991 24784 24784 W System.err: 	at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:279)
01-03 20:48:46.991 24784 24784 W System.err: 	at android.content.res.Resources.getResourceEntryName(Resources.java:2002)
01-03 20:48:46.991 24784 24784 W System.err: 	at com.lokalise.sdk.LokaliseResources.getText(LokaliseResources.kt:38)
01-03 20:48:46.991 24784 24784 W System.err: 	at android.content.Context.getText(Context.java:565)
01-03 20:48:46.991 24784 24784 W System.err: 	at yt2.a(PG:66)
01-03 20:48:46.991 24784 24784 W System.err: 	at yt2.a(PG:16)
01-03 20:48:46.991 24784 24784 W System.err: 	at yt2.a(PG:30)
01-03 20:48:46.991 24784 24784 W System.err: 	at org.chromium.content.browser.input.DateTimeChooserAndroid.createDateTimeChooser(PG:3)
01-03 20:48:46.991 24784 24784 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
01-03 20:48:46.991 24784 24784 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:326)
01-03 20:48:46.991 24784 24784 W System.err: 	at android.os.Looper.loop(Looper.java:165)
01-03 20:48:46.991 24784 24784 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6729)
01-03 20:48:46.991 24784 24784 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
01-03 20:48:46.991 24784 24784 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-03 20:48:46.991 24784 24784 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

**Additional information:**

**Comment by vilppuvuorinen** [comment]
I've reported the issue to Lokalise.

**Comment by balloob** [comment]
CC @bramkragten here is another Lokalise issue

**Comment by vilppuvuorinen** [comment]
The issue has been reproduced by Lokalise devs.

**Comment by vilppuvuorinen** [comment]
`com.lokalise.android:sdk:2.0.0-beta-5` should fix this issue.

**Comment by vilppuvuorinen** [comment]
The Lokalise update fixed the issue. Thanks.
