### ISSUE TITLE
Unable to add window -- token is not valid; is your activity running?

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#282]
**Home Assistant Android version:** 1.4.0 (77)

https://console.firebase.google.com/u/1/project/home-assistant-mobile-apps/crashlytics/app/android:io.homeassistant.companion.android/issues/09c81070c8f045dcc03f5a483b428815?time=last-seven-days&sessionId=5E27DADA01E80001188CD3F20FABBD19_DNE_0_v2

This crash is usually caused by your app trying to display a dialogue using a previously finished Activity as a context. For example, this can happen if an Activity triggers an AsyncTask that tries to display a dialogue when it is finished, but the user navigates back from the Activity before the task is completed. 

- [Android – Displaying Dialogs From Background Threads](http://dimitar.me/android-displaying-dialogs-from-background-threads)
- [Error : BinderProxy@45d459c0 is not valid; is your activity running?](http://stackoverflow.com/questions/7811993/error-binderproxy45d459c0-is-not-valid-is-your-activity-running)

```txt
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@5122463 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:1088)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
       at android.app.Dialog.show(Dialog.java:470)
       at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
       at io.homeassistant.companion.android.webview.WebViewActivity.showError(WebViewActivity.kt:288)
       at io.homeassistant.companion.android.webview.WebViewPresenterImpl$onGetExternalAuth$1.invokeSuspend(WebViewPresenterImpl.kt:42)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:334)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7188)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by JBassett** [comment]
Unable to reproduce on latest builds.

**Comment by BGchannell** [comment]
I have error with mod menu free fire game

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dts.freefireth/com.dts.freefireth.FFMainActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1524)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6239)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:699)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:347)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at android.app.Dialog.show(Dialog.java:332)
	at com.H4X.H4X.CriarLogin(H4X.java:345)
	at com.H4X.H4X.Start(H4X.java:105)
	at com.dts.freefireth.FFMainActivity.onCreate(Native Method)
	at android.app.Activity.performCreate(Activity.java:6875)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
	... 9 more
