### ISSUE TITLE
null cannot be cast to non-null type in SettingsFragment#onUrlChanged

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#283]
**Home Assistant Android version:** 1.4.0 (77)

https://console.firebase.google.com/u/1/project/home-assistant-mobile-apps/crashlytics/app/android:io.homeassistant.companion.android/issues/4e78dd333d1bb11a8faf1518c7eb7c32?time=last-seven-days&sessionId=5E27CA70027500012733CEA25A2E3FF5_DNE_0_v2

```txt
Fatal Exception: kotlin.TypeCastException: null cannot be cast to non-null type io.homeassistant.companion.android.common.dagger.GraphComponentAccessor
       at io.homeassistant.companion.android.settings.SettingsFragment.onUrlChanged(SettingsFragment.kt:68)
       at io.homeassistant.companion.android.settings.SettingsPresenterImpl.handleInternalUrlStatus(SettingsPresenterImpl.kt:94)
       at io.homeassistant.companion.android.settings.SettingsPresenterImpl$onCreate$1.invokeSuspend(SettingsPresenterImpl.kt:81)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by JBassett** [comment]
Unable to reproduce on latest builds.
