### ISSUE TITLE
IllegalStateException trying to call `popBack` after `onSaveInstanceState`

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#284]
**Home Assistant Android version:** 1.4.0 (77)

https://console.firebase.google.com/u/0/project/home-assistant-mobile-apps/crashlytics/app/android:io.homeassistant.companion.android/issues/b64861e4fc80b69bbe60dead55f62703?time=last-seven-days&sessionId=5E27B98902E700010761DE0D9E251865_DNE_0_v2

```txt
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
       at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
       at androidx.fragment.app.FragmentManagerImpl.popBackStack(FragmentManagerImpl.java:247)
       at io.homeassistant.companion.android.onboarding.authentication.AuthenticationFragment.popBack(AuthenticationFragment.kt:94)
       at io.homeassistant.companion.android.onboarding.authentication.AuthenticationFragment$onCreateView$$inlined$apply$lambda$1.onReceivedError(AuthenticationFragment.kt:66)
       at on.handleMessage(PG:128)
       at android.os.Handler.dispatchMessage(:19)
       at android.os.Looper.loop(:249)
       at android.app.ActivityThread.main(:98)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(:11)
       at com.android.internal.os.ZygoteInit.main(:282)
```

**Comment by balloob** [comment]
Seems to have been resolved. Only 1 user affected in last 7 days and that was on 1.4.0.
