### ISSUE TITLE
NullPointerException in HomeAssistantSearcher#onServiceFound

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#288]
**Home Assistant Android version:** 1.4.0 (85)

https://console.firebase.google.com/u/1/project/home-assistant-mobile-apps/crashlytics/app/android:io.homeassistant.companion.android/issues/4f8cd37e596681d55eef35b94c36aabe?time=last-seven-days&sessionId=5E2741B700D0000120C60FBDB0228757_DNE_0_v2

```txt
Fatal Exception: kotlin.KotlinNullPointerException
       at io.homeassistant.companion.android.onboarding.discovery.HomeAssistantSearcher$onServiceFound$1.onServiceResolved(HomeAssistantSearcher.kt:54)
       at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:369)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by balloob** [comment]
Hmm this was one user on a YOGA tablet. Probably just funky Android 🤷‍♂ .
