### ISSUE TITLE
Fatal Exception: java.net.ConnectException

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#324]
Introduced in 1.5.0. 73 crashes affecting 49 users.

**Home Assistant Android version:** 1.5.0

https://console.firebase.google.com/u/0/project/home-assistant-mobile-apps/crashlytics/app/android:io.homeassistant.companion.android/issues/efe1b428cbe3a32f4bcc60754a53797a?time=last-seven-days&sessionId=5E325D4D014F00012FAF7FB2AB2DA16F_DNE_0_v2

```txt
Caused by java.net.ConnectException: failed to connect after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
       at libcore.io.IoBridge.isConnected(IoBridge.java:278)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:187)
       at libcore.io.IoBridge.connect(IoBridge.java:129)
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
       [...]
       at io.homeassistant.companion.android.data.HomeAssistantRetrofit$$special$$inlined$-addInterceptor$1.intercept(Interceptor.kt:82)
       [...]
       at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by JBassett** [comment]
After digging into this it appears this is related the widget activity.  Should be fixed with
https://github.com/home-assistant/home-assistant-android/issues/407 in 1.7.1+
