### ISSUE TITLE
Incorrect services.yaml crashes widget UI. 

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#365]
Introduced in 1.6.0. 463 crashes affecting 305 users

https://console.firebase.google.com/u/0/project/home-assistant-mobile-apps/crashlytics/app/android:io.homeassistant.companion.android/issues/d70cfcd1e89ab1678b19df9eb1eef4c8?time=last-seven-days&sessionId=5E42048D0172000118F21F919BF764AE_DNE_0_v2

```
Fatal Exception: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
       at com.google.gson.Gson.fromJson(Gson.java:899)
       at com.google.gson.Gson.fromJson(Gson.java:852)
       at com.google.gson.Gson.fromJson(Gson.java:801)
       at com.google.gson.Gson.fromJson(Gson.java:773)
       at io.homeassistant.companion.android.widgets.ButtonWidget$callConfiguredService$1.invokeSuspend(ButtonWidget.kt:171)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by JBassett** [comment]
Relates to https://github.com/home-assistant/home-assistant-android/issues/352

**Comment by KBerstene** [comment]
I don't think this is actually incorrect service.yamls, I think this is actually related to the break that happened to old widgets from the 1.5.0 widget storage method to the 1.6.0 storage method.  Recreating the widgets will work, though we could add a try/catch block around the JSON->HashMap method to catch this error and treat it more gracefully.

**Comment by JBassett** [comment]
Fixed via https://github.com/home-assistant/home-assistant-android/pull/377
