### ISSUE TITLE
Notification crash if referenced image does not exist

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#368]
Introduced in 1.6.0. 118 crashes affecting 28 users.

https://console.firebase.google.com/u/0/project/home-assistant-mobile-apps/crashlytics/app/android:io.homeassistant.companion.android/issues/4237c777a67459cf24bcae4e4852d29c?time=last-seven-days&sessionId=5E415E4D02E300014C45C394E4A198B1_DNE_0_v2

```
Fatal Exception: java.io.FileNotFoundException: https://example.com/i_do_not_exist.jpg
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
       at java.net.URL.openStream(URL.java:1072)
       at io.homeassistant.companion.android.notifications.MessagingService$getImageBitmap$2.invokeSuspend(MessagingService.kt:167)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by JBassett** [comment]
Fixed via https://github.com/home-assistant/home-assistant-android/pull/356
