### ISSUE TITLE
No Activity found to handle Intent android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#369]
Introduced in 1.6.0. 95 crashes affecting 86 users.

https://console.firebase.google.com/u/0/project/home-assistant-mobile-apps/crashlytics/app/android:io.homeassistant.companion.android/issues/22796aaa97feeb1c6ae4e7b24d65e22a?time=last-seven-days&sessionId=5E421E4C0114000178298A76C98433FE_DNE_0_v2

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65537, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {io.homeassistant.companion.android/io.homeassistant.companion.android.onboarding.OnboardingActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS dat=package:io.homeassistant.companion.android }
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4144)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4187)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6188)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
```

**Comment by Kisty** [comment]
Hmm, seems like some devices don't support this (Samsung!?). Perhaps we can redirect them to just settings page like here but with a better message? https://github.com/kontalk/androidclient/commit/be78119687940545d3613ae0d4280f4068125f6a
